### ISSUE TITLE
 instruction memory and instruction fetch cycle

### ISSUE THREAD

**Issue by DanSciortino** [evs2012/16-Bit_Processor#6]
Implement the instruction memory and instruction fetch cycle (15 pts). Generate a testbench and show that it works by using a screenshot.

**Comment by evs2012** [comment]
Instruction Memory is implemented but not yet tested.

**Comment by evs2012** [comment]
The bulk of the fetch cycle is then left to the Program Counter and the adding everything to it. The top part of this picture:
https://github.com/evs2012/16-Bit_Processor/blob/master/Processor.PNG?raw=true

Probably to be done in the top level file which I guess doesn't exist yet

**Comment by evs2012** [comment]
Did it!
